"""add user_id to books and generation_jobs

Revision ID: cf9633cfc532
Revises: 60840a1f0253
Create Date: 2026-09-23 23:55:05.355036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9633cfc532'
down_revision: Union[str, None] = '60840a1f0253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Hand-edited from the autogenerated version: the columns can't be
    # added directly as NOT NULL because real rows already exist (David's
    # test book + generation job). Add nullable, backfill, THEN enforce
    # NOT NULL — the autogenerated version skipped straight to NOT NULL
    # and would have failed against this database.
    #
    # Backfill target is user id 1 — David's own account, the first (and
    # at this point only) user, created via create_user.py before this
    # migration was written. Anything pre-dating multiuser support belongs
    # to him by construction.
    op.add_column('books', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE books SET user_id = 1 WHERE user_id IS NULL")
    op.alter_column('books', 'user_id', nullable=False)
    op.drop_constraint(op.f('books_name_key'), 'books', type_='unique')
    op.create_unique_constraint('uq_book_per_user', 'books', ['user_id', 'name'])
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['id'])

    op.add_column('generation_jobs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE generation_jobs SET user_id = 1 WHERE user_id IS NULL")
    op.alter_column('generation_jobs', 'user_id', nullable=False)
    op.create_foreign_key(None, 'generation_jobs', 'users', ['user_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.drop_column('generation_jobs', 'user_id')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint('uq_book_per_user', 'books', type_='unique')
    op.create_unique_constraint(op.f('books_name_key'), 'books', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###
